name: ReadMe API Update

on:
  push:
    branches:
      - main

jobs:
  update-api:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo 📚
        uses: actions/checkout@v3

      - name: Install dependencies ✅
        run: |
          sudo apt install jq
          npm install -g rdme

      - name: Extract unique tags from JSON
        run: |
          cat orangehrm-v2.json | jq .paths[][]?.tags[] | uniq | sort > tag-list.txt

      - name: Update APIs for Admin module
        run: |
          cat tag-list.txt | grep Admin/ | sed 's/"/--tag "/' | tr '\n' ' ' | sed '1s/^/rdme openapi:reduce orangehrm-v2.json --out reduced.json /' > reduce-command.sh
          chmod +x reduce-command.sh
          ./reduce-command.sh
          sed -i 's/Admin\///' reduced.json
          sed -i 's/OrangeHRM Open Source : REST API v2 docs/Admin/' reduced.json
          jq '.components+={"securitySchemes": {"OAuth2": {"type":"oauth2", "flows": {"authorizationCode":{"authorizationUrl":"https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/authorize", "tokenUrl": "https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/token", "scopes":{}}}}}}' reduced.json > reduced-security.json
          rdme openapi reduced-security.json --key=${{ secrets.README_API_KEY }} --id=64d991ddaf28d60045b5184c
          rm reduce*

      - name: Update APIs for Attendance module
        run: |
          cat tag-list.txt | grep Attendance/ | sed 's/"/--tag "/' | tr '\n' ' ' | sed '1s/^/rdme openapi:reduce orangehrm-v2.json --out reduced.json /' > reduce-command.sh
          chmod +x reduce-command.sh
          ./reduce-command.sh
          sed -i 's/Attendance\///' reduced.json
          sed -i 's/OrangeHRM Open Source : REST API v2 docs/Attendance/' reduced.json
          jq '.components+={"securitySchemes": {"OAuth2": {"type":"oauth2", "flows": {"authorizationCode":{"authorizationUrl":"https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/authorize", "tokenUrl": "https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/token", "scopes":{}}}}}}' reduced.json > reduced-security.json
          rdme openapi reduced-security.json --key=${{ secrets.README_API_KEY }} --id=64d9a24303b86f002dc735ac
          rm reduce*

      - name: Update APIs for Buzz module
        run: |
          cat tag-list.txt | grep Buzz/ | sed 's/"/--tag "/' | tr '\n' ' ' | sed '1s/^/rdme openapi:reduce orangehrm-v2.json --out reduced.json /' > reduce-command.sh
          chmod +x reduce-command.sh
          ./reduce-command.sh
          sed -i 's/Buzz\///' reduced.json
          sed -i 's/OrangeHRM Open Source : REST API v2 docs/Buzz/' reduced.json
          jq '.components+={"securitySchemes": {"OAuth2": {"type":"oauth2", "flows": {"authorizationCode":{"authorizationUrl":"https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/authorize", "tokenUrl": "https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/token", "scopes":{}}}}}}' reduced.json > reduced-security.json
          rdme openapi reduced-security.json --key=${{ secrets.README_API_KEY }} --id=64d9b9cd0e2807000c15c42b
          rm reduce*

      - name: Update APIs for Claim module
        run: |
          cat tag-list.txt | grep Claim/ | sed 's/"/--tag "/' | tr '\n' ' ' | sed '1s/^/rdme openapi:reduce orangehrm-v2.json --out reduced.json /' > reduce-command.sh
          chmod +x reduce-command.sh
          ./reduce-command.sh
          sed -i 's/Claim\///' reduced.json
          sed -i 's/OrangeHRM Open Source : REST API v2 docs/Claim/' reduced.json
          jq '.components+={"securitySchemes": {"OAuth2": {"type":"oauth2", "flows": {"authorizationCode":{"authorizationUrl":"https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/authorize", "tokenUrl": "https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/token", "scopes":{}}}}}}' reduced.json > reduced-security.json
          rdme openapi reduced-security.json --key=${{ secrets.README_API_KEY }} --id=64d9c7739b3fd500382e1f3a
          rm reduce*

      - name: Update APIs for Core module
        run: |
          cat tag-list.txt | grep Core/ | sed 's/"/--tag "/' | tr '\n' ' ' | sed '1s/^/rdme openapi:reduce orangehrm-v2.json --out reduced.json /' > reduce-command.sh
          chmod +x reduce-command.sh
          ./reduce-command.sh
          sed -i 's/Core\///' reduced.json
          sed -i 's/OrangeHRM Open Source : REST API v2 docs/Core/' reduced.json
          jq '.components+={"securitySchemes": {"OAuth2": {"type":"oauth2", "flows": {"authorizationCode":{"authorizationUrl":"https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/authorize", "tokenUrl": "https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/token", "scopes":{}}}}}}' reduced.json > reduced-security.json
          rdme openapi reduced-security.json --key=${{ secrets.README_API_KEY }} --id=64d9c98f8446dc04ad4181cd
          rm reduce*

      - name: Update APIs for Dashboard module
        run: |
          cat tag-list.txt | grep Dashboard | sed 's/"/--tag "/' | tr '\n' ' ' | sed '1s/^/rdme openapi:reduce orangehrm-v2.json --out reduced.json /' > reduce-command.sh
          chmod +x reduce-command.sh
          ./reduce-command.sh
          sed -i 's/Dashboard\///' reduced.json
          sed -i 's/OrangeHRM Open Source : REST API v2 docs/Dashboard/' reduced.json
          jq '.components+={"securitySchemes": {"OAuth2": {"type":"oauth2", "flows": {"authorizationCode":{"authorizationUrl":"https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/authorize", "tokenUrl": "https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/token", "scopes":{}}}}}}' reduced.json > reduced-security.json
          rdme openapi reduced-security.json --key=${{ secrets.README_API_KEY }} --id=64d9dbe660f3f304a9175395
          rm reduce*

      - name: Update APIs for Directory module
        run: |
          cat tag-list.txt | grep Directory | sed 's/"/--tag "/' | tr '\n' ' ' | sed '1s/^/rdme openapi:reduce orangehrm-v2.json --out reduced.json /' > reduce-command.sh
          chmod +x reduce-command.sh
          ./reduce-command.sh
          sed -i 's/Directory\///' reduced.json
          sed -i 's/OrangeHRM Open Source : REST API v2 docs/Directory/' reduced.json
          jq '.components+={"securitySchemes": {"OAuth2": {"type":"oauth2", "flows": {"authorizationCode":{"authorizationUrl":"https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/authorize", "tokenUrl": "https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/token", "scopes":{}}}}}}' reduced.json > reduced-security.json
          rdme openapi reduced-security.json --key=${{ secrets.README_API_KEY }} --id=64dc57ab89a1ab0062cb7241
          rm reduce*

      - name: Update APIs for Leave module
        run: |
          cat tag-list.txt | grep Leave/ | sed 's/"/--tag "/' | tr '\n' ' ' | sed '1s/^/rdme openapi:reduce orangehrm-v2.json --out reduced.json /' > reduce-command.sh
          chmod +x reduce-command.sh
          ./reduce-command.sh
          sed -i 's/Leave\///' reduced.json
          sed -i 's/OrangeHRM Open Source : REST API v2 docs/Leave/' reduced.json
          jq '.components+={"securitySchemes": {"OAuth2": {"type":"oauth2", "flows": {"authorizationCode":{"authorizationUrl":"https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/authorize", "tokenUrl": "https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/token", "scopes":{}}}}}}' reduced.json > reduced-security.json
          rdme openapi reduced-security.json --key=${{ secrets.README_API_KEY }} --id=64ddac30839b4a00660b365a
          rm reduce*

      - name: Update APIs for Maintenance module
        run: |
          cat tag-list.txt | grep Maintenance/ | sed 's/"/--tag "/' | tr '\n' ' ' | sed '1s/^/rdme openapi:reduce orangehrm-v2.json --out reduced.json /' > reduce-command.sh
          chmod +x reduce-command.sh
          ./reduce-command.sh
          sed -i 's/Maintenance\///' reduced.json
          sed -i 's/OrangeHRM Open Source : REST API v2 docs/Maintenance/' reduced.json
          jq '.components+={"securitySchemes": {"OAuth2": {"type":"oauth2", "flows": {"authorizationCode":{"authorizationUrl":"https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/authorize", "tokenUrl": "https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/token", "scopes":{}}}}}}' reduced.json > reduced-security.json
          rdme openapi reduced-security.json --key=${{ secrets.README_API_KEY }} --id=64d9dee603b86f002dc9cca4
          rm reduce*

      - name: Update APIs for Mobile module
        run: |
          cat tag-list.txt | grep Mobile/ | sed 's/"/--tag "/' | tr '\n' ' ' | sed '1s/^/rdme openapi:reduce orangehrm-v2.json --out reduced.json /' > reduce-command.sh
          chmod +x reduce-command.sh
          ./reduce-command.sh
          sed -i 's/Mobile\///' reduced.json
          sed -i 's/OrangeHRM Open Source : REST API v2 docs/Mobile/' reduced.json
          jq '.components+={"securitySchemes": {"OAuth2": {"type":"oauth2", "flows": {"authorizationCode":{"authorizationUrl":"https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/authorize", "tokenUrl": "https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/token", "scopes":{}}}}}}' reduced.json > reduced-security.json
          rdme openapi reduced-security.json --key=${{ secrets.README_API_KEY }} --id=64d9e0beedc99200614d20fd
          rm reduce*

      - name: Update APIs for OAuth module
        run: |
          cat tag-list.txt | grep OAuth/ | sed 's/"/--tag "/' | tr '\n' ' ' | sed '1s/^/rdme openapi:reduce orangehrm-v2.json --out reduced.json /' > reduce-command.sh
          chmod +x reduce-command.sh
          ./reduce-command.sh
          sed -i 's/OAuth\///' reduced.json
          sed -i 's/OrangeHRM Open Source : REST API v2 docs/OAuth/' reduced.json
          jq '.components+={"securitySchemes": {"OAuth2": {"type":"oauth2", "flows": {"authorizationCode":{"authorizationUrl":"https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/authorize", "tokenUrl": "https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/token", "scopes":{}}}}}}' reduced.json > reduced-security.json
          rdme openapi reduced-security.json --key=${{ secrets.README_API_KEY }} --id=64dc593afad6f500191c4974
          rm reduce*

      - name: Update APIs for Performance module
        run: |
          cat tag-list.txt | grep Performance/ | sed 's/"/--tag "/' | tr '\n' ' ' | sed '1s/^/rdme openapi:reduce orangehrm-v2.json --out reduced.json /' > reduce-command.sh
          chmod +x reduce-command.sh
          ./reduce-command.sh
          sed -i 's/Performance\///' reduced.json
          sed -i 's/OrangeHRM Open Source : REST API v2 docs/Performance/' reduced.json
          jq '.components+={"securitySchemes": {"OAuth2": {"type":"oauth2", "flows": {"authorizationCode":{"authorizationUrl":"https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/authorize", "tokenUrl": "https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/token", "scopes":{}}}}}}' reduced.json > reduced-security.json
          rdme openapi reduced-security.json --key=${{ secrets.README_API_KEY }} --id=64db092c1c1318001f61b4c0
          rm reduce*

      - name: Update APIs for PIM module
        run: |
          cat tag-list.txt | grep PIM/ | sed 's/"/--tag "/' | tr '\n' ' ' | sed '1s/^/rdme openapi:reduce orangehrm-v2.json --out reduced.json /' > reduce-command.sh
          chmod +x reduce-command.sh
          ./reduce-command.sh
          sed -i 's/PIM\///' reduced.json
          sed -i 's/OrangeHRM Open Source : REST API v2 docs/PIM/' reduced.json
          jq '.components+={"securitySchemes": {"OAuth2": {"type":"oauth2", "flows": {"authorizationCode":{"authorizationUrl":"https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/authorize", "tokenUrl": "https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/token", "scopes":{}}}}}}' reduced.json > reduced-security.json
          rdme openapi reduced-security.json --key=${{ secrets.README_API_KEY }} --id=64ddab7473eaac00420bcd63
          rm reduce*

      - name: Update APIs for Recruitment module
        run: |
          cat tag-list.txt | grep Recruitment/ | sed 's/"/--tag "/' | tr '\n' ' ' | sed '1s/^/rdme openapi:reduce orangehrm-v2.json --out reduced.json /' > reduce-command.sh
          chmod +x reduce-command.sh
          ./reduce-command.sh
          sed -i 's/Recruitment\///' reduced.json
          sed -i 's/OrangeHRM Open Source : REST API v2 docs/Recruitment/' reduced.json
          jq '.components+={"securitySchemes": {"OAuth2": {"type":"oauth2", "flows": {"authorizationCode":{"authorizationUrl":"https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/authorize", "tokenUrl": "https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/token", "scopes":{}}}}}}' reduced.json > reduced-security.json
          rdme openapi reduced-security.json --key=${{ secrets.README_API_KEY }} --id=64dbcba5e43feb0020b75aff
          rm reduce*

      - name: Update APIs for Time module
        run: |
          cat tag-list.txt | grep Time/ | sed 's/"/--tag "/' | tr '\n' ' ' | sed '1s/^/rdme openapi:reduce orangehrm-v2.json --out reduced.json /' > reduce-command.sh
          chmod +x reduce-command.sh
          ./reduce-command.sh
          sed -i 's/Time\///' reduced.json
          sed -i 's/OrangeHRM Open Source : REST API v2 docs/Time/' reduced.json
          jq '.components+={"securitySchemes": {"OAuth2": {"type":"oauth2", "flows": {"authorizationCode":{"authorizationUrl":"https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/authorize", "tokenUrl": "https://opensource-demo.orangehrmlive.com/web/index.php/oauth2/token", "scopes":{}}}}}}' reduced.json > reduced-security.json
          rdme openapi reduced-security.json --key=${{ secrets.README_API_KEY }} --id=64dc4cdebd55a7001e859ee8
          rm reduce*